#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    time = int(s[:2])
    if s[-2:] == 'PM' and time!=12 and time>=1:
        time+= 12
    elif s[-2:] == 'AM' and time== 12:
        time = 0
    return '{t:02d}{md}'.format(t=time, md=s[2:-2])
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
